[tool.poetry]
name = "shipstation-client"
version = "0.1.0"
description = 'Python bindings for the ShipStation API'
license = "MIT"
authors = ["AgriTheory <hello@agritheory.com>"]
readme = "README.md"
homepage = "https://github.com/agritheory/shipstation-client"
repository = "https://github.com/agritheory/shipstation-client"
keywords = ['shipstation', 'client', 'api', 'python', 'orders', 'shipments']
packages = [{ include = "shipstation" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Web Environment",
  "Framework :: Pytest",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
attrs = "^23.2.0"
cattrs = "^23.2.3"
httpx = "^0.27.0"
python-dateutil = "^2.8.1"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.8"
black = "^24.4.2"
darglint = "^1.8.1"
isort = "^5.13.2"
mypy = "^1.10.0"
pre-commit = "^3.7.1"
pydocstyle = "^5.0.2"
pytest = "^8.2.1"
pytest-asyncio = "^0.23.7"
pytest-cov = "^5.0.0"
pytest-httpx = "^0.30.0"
pytest-mypy = "^0.10.3"
python-dotenv = "^0.13.0"
pyupgrade = "^3.15.2"
respx = "^0.21.1"
safety = "^3.2.0"
typing-extensions = "^4.12.2"

[tool.pytest.ini_options]
addopts = "--cov=shipstation --cov-report term"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"

[tool.tox]
legacy_tox_ini = """
[tox]
min_version = 4
requires =
    tox-gh-actions>=3
envlist = py310, py311, py312, linting
[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312, linting
[testenv]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
[testenv:linting]
description = run linters
commands_pre =
    poetry install
    python -m pip install flake8
    python -m pip install mypy
    python -m pip install black git+https://github.com/agritheory/black.git
    mypy ./ --install-types --non-interactive
commands =
    flake8 ./shipstation
    mypy ./shipstation --ignore-missing-imports
    black --check .
[testenv:py310]
description = run pytest on 3.10
commands =
    pytest tests/ --disable-warnings -s
[testenv:py311]
description = run pytest on 3.11
commands =
    pytest tests/ --disable-warnings -s
[testenv:py312]
description = run pytest and coverage on 3.12
commands =
    pytest tests/ --cov=shipstation --cov-report=xml --disable-warnings -s
"""

[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variable = [
    "shipstation/__init__.py:__version__"
]

[tool.semantic_release.branches.version]
match = "master"
