LIST_TAGS = [{"color": "#FFFFFF", "name": "Amazon Prime Order", "tagId": 12345}]

LIST_MARKETPLACES = [
    {
        "canConfirmShipments": True,
        "canRefresh": True,
        "marketplaceId": 23,
        "name": "3dcart",
        "supportsCustomMappings": True,
        "supportsCustomStatuses": False,
    },
    {
        "canConfirmShipments": True,
        "canRefresh": True,
        "marketplaceId": 115,
        "name": "Acumatica",
        "supportsCustomMappings": False,
        "supportsCustomStatuses": True,
    },
]

LIST_STORES = [
    {
        "accountName": "ABC123456789",
        "active": True,
        "autoRefresh": True,
        "companyName": "411Seasons",
        "createDate": "2017-03-01T13:57:49.033",
        "email": "",
        "integrationUrl": "",
        "lastRefreshAttempt": "2020-06-23T11:56:51.627",
        "marketplaceId": 2,
        "marketplaceName": "Amazon",
        "modifyDate": "2017-05-15T07:28:54.357",
        "phone": "",
        "publicEmail": "",
        "refreshDate": "2020-06-23T11:56:51.377",
        "statusMappings": "",
        "storeId": 34567,
        "storeName": "Mexico Amazon Store",
        "website": "",
    },
    {
        "accountName": "DEF123456789",
        "active": True,
        "autoRefresh": True,
        "companyName": "",
        "createDate": "2017-01-25T14:38:33.793",
        "email": "",
        "integrationUrl": "",
        "lastRefreshAttempt": "2020-06-23T07:12:32.217",
        "marketplaceId": 2,
        "marketplaceName": "Amazon",
        "modifyDate": "2017-01-25T14:39:25.003",
        "phone": "",
        "publicEmail": "",
        "refreshDate": "2020-06-23T07:12:31.95",
        "statusMappings": "",
        "storeId": 23456,
        "storeName": "CA Amazon Store",
        "website": "",
    },
    {
        "accountName": "GHI123456789",
        "active": True,
        "autoRefresh": True,
        "companyName": "",
        "createDate": "2017-01-23T13:55:39.643",
        "email": "",
        "integrationUrl": "",
        "lastRefreshAttempt": "2020-06-23T11:43:20.947",
        "marketplaceId": 2,
        "marketplaceName": "Amazon",
        "modifyDate": "2018-06-05T06:48:42.98",
        "phone": "",
        "publicEmail": "",
        "refreshDate": "2020-06-23T11:43:20.713",
        "statusMappings": "",
        "storeId": 12345,
        "storeName": "US Amazon Store",
        "website": "",
    },
]

GET_STORE = {
    "accountName": "GHI123456789",
    "active": True,
    "autoRefresh": True,
    "companyName": "",
    "createDate": "2017-01-23T13:55:39.643",
    "email": "",
    "integrationUrl": "",
    "lastRefreshAttempt": "2020-06-23T11:43:20.947",
    "marketplaceId": 2,
    "marketplaceName": "Amazon",
    "modifyDate": "2018-06-05T06:48:42.98",
    "phone": "",
    "publicEmail": "",
    "refreshDate": "2020-06-23T11:43:20.713",
    "statusMappings": "",
    "storeId": 12345,
    "storeName": "US Amazon Store",
    "website": "",
}


LIST_USERS = [
    {
        "name": "Merchandising",
        "userId": "57f4e49d-777e-4708-8b26-fd836fc975e6",
        "userName": "merchandising@example.com",
    },
    {
        "name": "Marketing",
        "userId": "0dbc3f54-5cd4-4054-b2b5-92427e18d6cd",
        "userName": "marketing@example.com",
    },
]


LIST_WAREHOUSES = [
    {
        "createDate": "2020-04-07T12:03:46.4000000",
        "extInventoryIdentity": "",
        "isDefault": False,
        "originAddress": {
            "addressVerified": "Address validated successfully",
            "city": "Anywhere",
            "company": "",
            "country": "US",
            "name": "Warehouse 1",
            "phone": "18005551234",
            "postalCode": "12345",
            "residential": False,
            "state": "WA",
            "street1": "123 Long St",
            "street2": "Unit 4",
            "street3": "",
        },
        "registerFedexMeter": "",
        "returnAddress": {
            "addressVerified": "Address validated successfully",
            "city": "Anywhere",
            "company": "Test Company",
            "country": "US",
            "name": "",
            "phone": "18005553214",
            "postalCode": "23456",
            "residential": "",
            "state": "ID",
            "street1": "0 Short St",
            "street2": "",
            "street3": "",
        },
        "sellerIntegrationId": "",
        "warehouseId": 456789,
        "warehouseName": "Test Company",
    },
    {
        "createDate": "2015-10-23T10:03:36.3130000",
        "extInventoryIdentity": "",
        "isDefault": False,
        "originAddress": {
            "addressVerified": "Address validated successfully",
            "city": "Big City",
            "company": "Another LLC",
            "country": "US",
            "name": "Virtual Warehouse",
            "phone": "5555555555",
            "postalCode": "98765",
            "residential": False,
            "state": "OR",
            "street1": "150000000 900th Street SE",
            "street2": "Suite C",
            "street3": "",
        },
        "registerFedexMeter": "",
        "returnAddress": {
            "addressVerified": "Address validated successfully",
            "city": "Big City",
            "company": "Another LLC",
            "country": "US",
            "name": "Virtual Warehouse",
            "phone": "5555555555",
            "postalCode": "98765",
            "residential": False,
            "state": "OR",
            "street1": "150000000 900th Street SE",
            "street2": "Suite C",
            "street3": "",
        },
        "sellerIntegrationId": "",
        "warehouseId": 123456,
        "warehouseName": "Another LLC Warehouse",
    },
]


LIST_WEBHOOKS = [
    {
        "IsLabelAPIHook": False,
        "WebHookID": 123,
        "SellerID": 100000,
        "StoreID": 12345,
        "HookType": "ITEM_ORDER_NOTIFY",
        "MessageFormat": "Json",
        "Url": "http://example.endpoint/orders",
        "Name": "My Order Webhook",
        "BulkCopyBatchID": None,
        "BulkCopyRecordID": None,
        "Active": True,
        "WebhookLogs": [],
        "Seller": None,
        "Store": None,
    },
    {
        "IsLabelAPIHook": False,
        "WebHookID": 456,
        "SellerID": 100000,
        "StoreID": 98765,
        "HookType": "SHIP_NOTIFY",
        "MessageFormat": "Json",
        "Url": "https://example.endpoint/shipment",
        "Name": "My Shipment Webhook",
        "BulkCopyBatchID": None,
        "BulkCopyRecordID": None,
        "Active": True,
        "WebhookLogs": [],
        "Seller": None,
        "Store": None,
    },
]


LIST_CARRIERS = [
    {
        "accountNumber": "abc123456789",
        "balance": 15.01,
        "code": "stamps_com",
        "name": "Stamps.com",
        "nickname": "",
        "primary": True,
        "requiresFundedAccount": True,
        "shippingProviderId": 35725,
    },
    {
        "accountNumber": "36598-7894",
        "balance": 0.21,
        "code": "ups",
        "name": "UPS",
        "nickname": "UPS",
        "primary": True,
        "requiresFundedAccount": False,
        "shippingProviderId": 57765,
    },
]

LIST_SERVICES = [
    {
        "carrierCode": "stamps_com",
        "code": "usps_first_class_mail",
        "domestic": True,
        "international": False,
        "name": "USPS First Class Mail",
    },
    {
        "carrierCode": "stamps_com",
        "code": "usps_media_mail",
        "domestic": True,
        "international": False,
        "name": "USPS Media Mail",
    },
    {
        "carrierCode": "stamps_com",
        "code": "usps_parcel_select",
        "domestic": True,
        "international": False,
        "name": "USPS Parcel Select Ground",
    },
]


LIST_PACKAGES = [
    {
        "carrierCode": "stamps_com",
        "code": "package",
        "domestic": True,
        "international": True,
        "name": "Package",
    },
    {
        "carrierCode": "stamps_com",
        "code": "flat_rate_envelope",
        "domestic": True,
        "international": True,
        "name": "Flat Rate Envelope",
    },
]


LIST_CUSTOMERS = {
    "customers": [
        {
            "addressVerified": "Verified",
            "city": "BIG TOWN",
            "company": "",
            "countryCode": "US",
            "createDate": "2017-12-16T18:49:16.0070000",
            "customerId": 123456789,
            "email": "yep@example.com",
            "marketplaceUsernames": [
                {
                    "createDate": "2017-12-16T18:49:16.0200000",
                    "customerId": 123456789,
                    "customerUserId": 123456789,
                    "marketplace": "Amazon",
                    "marketplaceId": 2,
                    "modifyDate": "2017-12-16T18:49:16.0200000",
                    "username": "yep@example.com",
                }
            ],
            "modifyDate": "2017-12-16T18:49:16.0070000",
            "name": "Yep Example",
            "phone": "",
            "postalCode": "99999-1234",
            "state": "FL",
            "street1": "1 E 1ST ST",
            "street2": "",
            "tags": "",
        },
        {
            "addressVerified": "Verified",
            "city": "KEY WEST",
            "company": "",
            "countryCode": "US",
            "createDate": "2017-05-26T06:12:02.6230000",
            "customerId": 987654321,
            "email": "nope@yahoo.com",
            "marketplaceUsernames": [
                {
                    "createDate": "2017-05-26T06:12:02.6400000",
                    "customerId": 987654321,
                    "customerUserId": 987654321,
                    "marketplace": "Amazon",
                    "marketplaceId": 2,
                    "modifyDate": "2017-05-26T06:12:02.6400000",
                    "username": "nope@yahoo.com",
                }
            ],
            "modifyDate": "2017-05-26T06:12:02.6230000",
            "name": "Arbitrary LLC",
            "phone": "123 568 1234",
            "postalCode": "99999-1234",
            "state": "FL",
            "street1": "6000 Beach St",
            "street2": "",
            "tags": "",
        },
    ]
}


GET_CARRIER = {
    "accountNumber": "example",
    "balance": 15.01,
    "code": "stamps_com",
    "name": "Stamps.com",
    "nickname": "",
    "primary": True,
    "requiresFundedAccount": True,
    "shippingProviderId": 35725,
}


GET_CUSTOMER = {
    "addressVerified": "Verified",
    "city": "BIG TOWN",
    "company": "",
    "countryCode": "US",
    "createDate": "2017-12-16T18:49:16.0070000",
    "customerId": 123456789,
    "email": "yep@example.com",
    "marketplaceUsernames": [
        {
            "createDate": "2017-12-16T18:49:16.0200000",
            "customerId": 123456789,
            "customerUserId": 123456789,
            "marketplace": "Amazon",
            "marketplaceId": 2,
            "modifyDate": "2017-12-16T18:49:16.0200000",
            "username": "yep@example.com",
        }
    ],
    "modifyDate": "2017-12-16T18:49:16.0070000",
    "name": "Yep Example",
    "phone": "",
    "postalCode": "99999-1234",
    "state": "FL",
    "street1": "1 E 1ST ST",
    "street2": "",
    "tags": "",
}


LIST_ORDERS = {
    "orders": [
        {
            "advancedOptions": {
                "billToAccount": None,
                "billToCountryCode": None,
                "billToMyOtherAccount": None,
                "billToParty": None,
                "billToPostalCode": None,
                "containsAlcohol": False,
                "customField1": "EARLY BIRD SPECIAL",
                "customField2": "",
                "customField3": None,
                "mergedIds": [],
                "mergedOrSplit": False,
                "nonMachinable": False,
                "parentId": None,
                "saturdayDelivery": False,
                "source": "Manual Orders",
                "storeId": 12345,
                "warehouseId": 12345,
            },
            "amountPaid": 0.0,
            "billTo": {
                "addressVerified": None,
                "city": None,
                "company": None,
                "country": None,
                "name": "Todd Ledet",
                "phone": None,
                "postalCode": None,
                "residential": None,
                "state": None,
                "street1": None,
                "street2": None,
                "street3": None,
            },
            "carrierCode": "stamps_com",
            "confirmation": "none",
            "createDate": "2015-06-29T13:05:13.4930000",
            "customerEmail": "nope@example.com",
            "customerId": None,
            "customerNotes": None,
            "customerUsername": None,
            "dimensions": None,
            "externallyFulfilled": False,
            "externallyFulfilledBy": None,
            "gift": False,
            "giftMessage": None,
            "holdUntilDate": None,
            "insuranceOptions": {
                "insureShipment": False,
                "insuredValue": 0.0,
                "provider": None,
            },
            "internalNotes": None,
            "internationalOptions": {
                "contents": None,
                "customsItems": None,
                "nonDelivery": None,
            },
            "items": [],
            "labelMessages": None,
            "modifyDate": "2015-06-29T14:30:07.8970000",
            "orderDate": "2015-05-19T15:35:00.0000000",
            "orderId": 123456789,
            "orderKey": "123456789",
            "orderNumber": "123456789",
            "orderStatus": "shipped",
            "orderTotal": 7.0,
            "packageCode": "package",
            "paymentDate": "2015-06-29T13:05:13.4930000",
            "paymentMethod": None,
            "requestedShippingService": "USPS First Class Mail",
            "serviceCode": "usps_first_class_mail",
            "shipByDate": None,
            "shipDate": "2015-06-29",
            "shipTo": {
                "addressVerified": "Address validated successfully",
                "city": "ST MUNICIPALITY",
                "company": None,
                "country": "US",
                "name": "Todd Ledet",
                "phone": None,
                "postalCode": "12345-9876",
                "residential": True,
                "state": "IA",
                "street1": "9 DUG ST",
                "street2": "",
                "street3": None,
            },
            "shippingAmount": 0.0,
            "tagIds": None,
            "taxAmount": 0.0,
            "userId": None,
            "weight": {"WeightUnits": 1, "units": "ounces", "value": 5.0},
        },
        {
            "advancedOptions": {
                "billToAccount": None,
                "billToCountryCode": None,
                "billToMyOtherAccount": None,
                "billToParty": None,
                "billToPostalCode": None,
                "containsAlcohol": False,
                "customField1": "EARLY BIRD SPECIAL",
                "customField2": "",
                "customField3": None,
                "mergedIds": [],
                "mergedOrSplit": False,
                "nonMachinable": False,
                "parentId": None,
                "saturdayDelivery": False,
                "source": None,
                "storeId": 12345,
                "warehouseId": 12345,
            },
            "amountPaid": 0.0,
            "billTo": {
                "addressVerified": None,
                "city": None,
                "company": None,
                "country": None,
                "name": "Nope Example",
                "phone": None,
                "postalCode": None,
                "residential": None,
                "state": None,
                "street1": None,
                "street2": None,
                "street3": None,
            },
            "carrierCode": "express_1",
            "confirmation": "none",
            "createDate": "2015-06-30T15:20:26.7230000",
            "customerEmail": "nope@example.com",
            "customerId": None,
            "customerNotes": None,
            "customerUsername": None,
            "dimensions": None,
            "externallyFulfilled": False,
            "externallyFulfilledBy": None,
            "gift": False,
            "giftMessage": None,
            "holdUntilDate": None,
            "insuranceOptions": {
                "insureShipment": False,
                "insuredValue": 0.0,
                "provider": None,
            },
            "internalNotes": None,
            "internationalOptions": {
                "contents": "merchandise",
                "customsItems": [
                    {
                        "countryOfOrigin": "CN",
                        "customsItemId": 13461125,
                        "description": "Suspicious Munitions",
                        "harmonizedTariffCode": "",
                        "quantity": 1,
                        "value": 7.0,
                    }
                ],
                "nonDelivery": "return_to_sender",
            },
            "items": [],
            "labelMessages": None,
            "modifyDate": "2015-06-30T18:47:11.8870000",
            "orderDate": "2015-05-19T21:24:00.0000000",
            "orderId": 123456789,
            "orderKey": "123456789",
            "orderNumber": "123456789",
            "orderStatus": "shipped",
            "orderTotal": 0.0,
            "packageCode": "package",
            "paymentDate": "2015-06-30T15:20:26.7230000",
            "paymentMethod": None,
            "requestedShippingService": "USPS First Class Mail Intl",
            "serviceCode": "usps_first_class_package_international",
            "shipByDate": None,
            "shipDate": "2015-07-01",
            "shipTo": {
                "addressVerified": "Address not yet validated",
                "city": "Large City",
                "company": None,
                "country": "IN",
                "name": "Nope Example",
                "phone": None,
                "postalCode": "100000",
                "residential": False,
                "state": None,
                "street1": "6 Bustling St",
                "street2": "Near Flower Market",
                "street3": "Maharashtra",
            },
            "shippingAmount": 0.0,
            "tagIds": None,
            "taxAmount": 0.0,
            "userId": None,
            "weight": {"WeightUnits": 1, "units": "ounces", "value": 5.0},
        },
    ],
    "page": 1,
    "pages": 1,
    "total": 2,
}


GET_ORDER = {
    "advancedOptions": {
        "billToAccount": None,
        "billToCountryCode": None,
        "billToMyOtherAccount": None,
        "billToParty": None,
        "billToPostalCode": None,
        "containsAlcohol": False,
        "customField1": "EARLY BIRD SPECIAL",
        "customField2": "",
        "customField3": None,
        "mergedIds": [],
        "mergedOrSplit": False,
        "nonMachinable": False,
        "parentId": None,
        "saturdayDelivery": False,
        "source": None,
        "storeId": 12345,
        "warehouseId": 12345,
    },
    "amountPaid": 0.0,
    "billTo": {
        "addressVerified": None,
        "city": None,
        "company": None,
        "country": None,
        "name": "Sandro Pigoni",
        "phone": None,
        "postalCode": None,
        "residential": None,
        "state": None,
        "street1": None,
        "street2": None,
        "street3": None,
    },
    "carrierCode": "stamps_com",
    "confirmation": "delivery",
    "createDate": "2015-06-30T15:20:26.7230000",
    "customerEmail": "s.pigoni@gmail.com",
    "customerId": None,
    "customerNotes": None,
    "customerUsername": None,
    "dimensions": None,
    "externallyFulfilled": False,
    "externallyFulfilledBy": None,
    "gift": False,
    "giftMessage": None,
    "holdUntilDate": None,
    "insuranceOptions": {
        "insureShipment": False,
        "insuredValue": 0.0,
        "provider": None,
    },
    "internalNotes": None,
    "internationalOptions": {
        "contents": "merchandise",
        "customsItems": [
            {
                "countryOfOrigin": "CN",
                "customsItemId": 123456789,
                "description": "Example Item",
                "harmonizedTariffCode": "",
                "quantity": 1,
                "value": 7.0,
            }
        ],
        "nonDelivery": "return_to_sender",
    },
    "items": [],
    "labelMessages": None,
    "modifyDate": "2015-06-30T18:47:32.9330000",
    "orderDate": "2015-06-02T05:58:00.0000000",
    "orderId": 123456789,
    "orderKey": "123456789",
    "orderNumber": "123456789",
    "orderStatus": "shipped",
    "orderTotal": 0.0,
    "packageCode": "package",
    "paymentDate": "2015-06-30T15:20:26.7230000",
    "paymentMethod": None,
    "requestedShippingService": "USPS First Class Mail Intl",
    "serviceCode": "usps_first_class_package_international",
    "shipByDate": None,
    "shipDate": "2015-07-01",
    "shipTo": {
        "addressVerified": "Address not yet validated",
        "city": "Luzern",
        "company": None,
        "country": "CH",
        "name": "Nope Example",
        "phone": None,
        "postalCode": "5000",
        "residential": False,
        "state": "",
        "street1": "Weystrasse",
        "street2": "0",
        "street3": None,
    },
    "shippingAmount": 0.0,
    "tagIds": None,
    "taxAmount": 0.0,
    "userId": None,
    "weight": {"WeightUnits": 1, "units": "ounces", "value": 5.0},
}


GET_PRODUCT = {
    "active": True,
    "aliases": None,
    "createDate": "2016-10-31T07:43:00.203",
    "customsCountryCode": None,
    "customsDescription": None,
    "customsTariffNo": None,
    "customsValue": None,
    "defaultCarrierCode": None,
    "defaultConfirmation": None,
    "defaultCost": None,
    "defaultIntlCarrierCode": None,
    "defaultIntlConfirmation": None,
    "defaultIntlPackageCode": None,
    "defaultIntlServiceCode": None,
    "defaultPackageCode": None,
    "defaultServiceCode": None,
    "fulfillmentSku": "019372892403",
    "height": None,
    "internalNotes": None,
    "length": None,
    "modifyDate": "2017-01-16T06:58:26.05",
    "name": "Example product",
    "noCustoms": None,
    "price": 0.0,
    "productCategory": None,
    "productId": 123456789,
    "productType": None,
    "sku": " ABC123456789",
    "tags": None,
    "warehouseLocation": None,
    "weightOz": 5.0,
    "width": None,
}


GET_RATES = [
    {
        "otherCost": 0.0,
        "serviceCode": "usps_first_class_mail",
        "serviceName": "USPS First Class Mail - Large Envelope or Flat",
        "shipmentCost": 3.2,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_first_class_mail",
        "serviceName": "USPS First Class Mail - Package",
        "shipmentCost": 3.93,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Package",
        "shipmentCost": 7.02,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Medium Flat Rate Box",
        "shipmentCost": 13.2,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Small Flat Rate Box",
        "shipmentCost": 7.65,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Large Flat Rate Box",
        "shipmentCost": 18.3,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Flat Rate Envelope",
        "shipmentCost": 7.15,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Flat Rate Padded Envelope",
        "shipmentCost": 7.75,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Regional Rate Box A",
        "shipmentCost": 7.68,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Regional Rate Box B",
        "shipmentCost": 8.07,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail",
        "serviceName": "USPS Priority Mail - Legal Flat Rate Envelope",
        "shipmentCost": 7.45,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail_express",
        "serviceName": "USPS Priority Mail Express - Package",
        "shipmentCost": 23.0,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail_express",
        "serviceName": "USPS Priority Mail Express - Flat Rate Envelope",
        "shipmentCost": 22.75,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail_express",
        "serviceName": "USPS Priority Mail Express - Flat Rate Padded Envelope",
        "shipmentCost": 23.25,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_priority_mail_express",
        "serviceName": "USPS Priority Mail Express - Legal Flat Rate Envelope",
        "shipmentCost": 22.95,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_media_mail",
        "serviceName": "USPS Media Mail - Package",
        "shipmentCost": 2.8,
    },
    {
        "otherCost": 0.0,
        "serviceCode": "usps_parcel_select",
        "serviceName": "USPS Parcel Select Ground - Package",
        "shipmentCost": 6.92,
    },
]

GET_WAREHOUSE = {
    "createDate": "2020-04-07T12:03:46.4000000",
    "extInventoryIdentity": "",
    "isDefault": False,
    "originAddress": {
        "addressVerified": "Address validated successfully",
        "city": "Anywhere",
        "company": "",
        "country": "US",
        "name": "Warehouse 1",
        "phone": "18005551234",
        "postalCode": "12345",
        "residential": False,
        "state": "WA",
        "street1": "123 Long St",
        "street2": "Unit 4",
        "street3": "",
    },
    "registerFedexMeter": "",
    "returnAddress": {
        "addressVerified": "Address validated successfully",
        "city": "Anywhere",
        "company": "Test Company",
        "country": "US",
        "name": "",
        "phone": "18005553214",
        "postalCode": "23456",
        "residential": "",
        "state": "ID",
        "street1": "0 Short St",
        "street2": "",
        "street3": "",
    },
    "sellerIntegrationId": "",
    "warehouseId": 456789,
    "warehouseName": "Test Company",
}


LIST_PRODUCTS = {
    "page": 1,
    "pages": 1,
    "products": [
        {
            "active": True,
            "aliases": None,
            "createDate": "2015-08-13T14:30:31.007",
            "customsCountryCode": None,
            "customsDescription": None,
            "customsTariffNo": None,
            "customsValue": None,
            "defaultCarrierCode": None,
            "defaultConfirmation": None,
            "defaultCost": None,
            "defaultIntlCarrierCode": None,
            "defaultIntlConfirmation": None,
            "defaultIntlPackageCode": None,
            "defaultIntlServiceCode": None,
            "defaultPackageCode": None,
            "defaultServiceCode": None,
            "fulfillmentSku": "712392290692",
            "height": None,
            "internalNotes": None,
            "length": None,
            "modifyDate": "2016-12-13T07:29:05.937",
            "name": "Example Product 0",
            "noCustoms": None,
            "price": 11.99,
            "productCategory": None,
            "productId": 987654321,
            "productType": None,
            "sku": "987654321",
            "tags": None,
            "warehouseLocation": None,
            "weightOz": 3.0,
            "width": None,
        },
        {
            "active": True,
            "aliases": None,
            "createDate": "2015-08-13T14:30:31.007",
            "customsCountryCode": None,
            "customsDescription": None,
            "customsTariffNo": None,
            "customsValue": None,
            "defaultCarrierCode": None,
            "defaultConfirmation": None,
            "defaultCost": None,
            "defaultIntlCarrierCode": None,
            "defaultIntlConfirmation": None,
            "defaultIntlPackageCode": None,
            "defaultIntlServiceCode": None,
            "defaultPackageCode": None,
            "defaultServiceCode": None,
            "fulfillmentSku": "712392289948",
            "height": None,
            "internalNotes": "0468437",
            "length": None,
            "modifyDate": "2015-10-01T07:06:53.82",
            "name": "Example Product 1",
            "noCustoms": None,
            "price": 11.99,
            "productCategory": None,
            "productId": 18139199,
            "productType": None,
            "sku": "KYGGBIP5",
            "tags": None,
            "warehouseLocation": None,
            "weightOz": 3.0,
            "width": None,
        },
    ],
    "total": 2,
}


LIST_SHIPMENTS = {
    "page": 1,
    "pages": 1,
    "shipments": [
        {
            "advancedOptions": {
                "billToAccount": None,
                "billToCountryCode": None,
                "billToParty": None,
                "billToPostalCode": None,
                "storeId": 12345,
            },
            "batchNumber": "100002",
            "carrierCode": "stamps_com",
            "confirmation": "delivery",
            "createDate": "2015-06-29T14:29:28.5830000",
            "customerEmail": "nope@example.com",
            "dimensions": None,
            "formData": None,
            "insuranceCost": 0.0,
            "insuranceOptions": {
                "insureShipment": False,
                "insuredValue": 0.0,
                "provider": None,
            },
            "isReturnLabel": False,
            "labelData": None,
            "marketplaceNotified": True,
            "notifyErrorMessage": None,
            "orderId": 123456789,
            "orderKey": "123456789",
            "orderNumber": "123456789",
            "packageCode": "package",
            "serviceCode": "usps_first_class_mail",
            "shipDate": "2015-06-29",
            "shipTo": {
                "addressVerified": None,
                "city": "CUT OFF",
                "company": None,
                "country": "US",
                "name": "Nope Example",
                "phone": None,
                "postalCode": "99999-1234",
                "residential": None,
                "state": "NY",
                "street1": "123 First St",
                "street2": "",
                "street3": None,
            },
            "shipmentCost": 2.35,
            "shipmentId": 123456789,
            "shipmentItems": None,
            "trackingNumber": "9400111899562764298812",
            "userId": "3c16cdda-af71-449f-b3da-0ea71f0f6954",
            "voidDate": None,
            "voided": False,
            "warehouseId": 37675,
            "weight": {"WeightUnits": 1, "units": "ounces", "value": 6.0},
        },
        {
            "advancedOptions": {
                "billToAccount": None,
                "billToCountryCode": None,
                "billToParty": None,
                "billToPostalCode": None,
                "storeId": 12345,
            },
            "batchNumber": "100002",
            "carrierCode": "stamps_com",
            "confirmation": "delivery",
            "createDate": "2015-06-29T14:29:28.5830000",
            "customerEmail": "yep@example.com",
            "dimensions": None,
            "formData": None,
            "insuranceCost": 0.0,
            "insuranceOptions": {
                "insureShipment": False,
                "insuredValue": 0.0,
                "provider": None,
            },
            "isReturnLabel": False,
            "labelData": None,
            "marketplaceNotified": True,
            "notifyErrorMessage": None,
            "orderId": 234567890,
            "orderKey": "234567890",
            "orderNumber": "234567890",
            "packageCode": "package",
            "serviceCode": "usps_first_class_mail",
            "shipDate": "2015-06-29",
            "shipTo": {
                "addressVerified": None,
                "city": "BOISE",
                "company": None,
                "country": "US",
                "name": "A. Nother Example",
                "phone": None,
                "postalCode": "12345-9999",
                "residential": None,
                "state": "ME",
                "street1": "0 Short St",
                "street2": "",
                "street3": None,
            },
            "shipmentCost": 2.35,
            "shipmentId": 101027951,
            "shipmentItems": None,
            "trackingNumber": "9400111899562764290564",
            "userId": "2bc927bb-22ba-41e5-b24f-087164eb5cc8",
            "voidDate": None,
            "voided": False,
            "warehouseId": 12345,
            "weight": {"WeightUnits": 1, "units": "ounces", "value": 6.0},
        },
        {
            "advancedOptions": {
                "billToAccount": None,
                "billToCountryCode": None,
                "billToParty": None,
                "billToPostalCode": None,
                "storeId": 12345,
            },
            "batchNumber": "100002",
            "carrierCode": "stamps_com",
            "confirmation": "delivery",
            "createDate": "2015-06-29T14:29:28.5830000",
            "customerEmail": "another@example.com",
            "dimensions": None,
            "formData": None,
            "insuranceCost": 0.0,
            "insuranceOptions": {
                "insureShipment": False,
                "insuredValue": 0.0,
                "provider": None,
            },
            "isReturnLabel": False,
            "labelData": None,
            "marketplaceNotified": True,
            "notifyErrorMessage": None,
            "orderId": 345678901,
            "orderKey": "345678901",
            "orderNumber": "345678901",
            "packageCode": "package",
            "serviceCode": "usps_first_class_mail",
            "shipDate": "2015-06-29",
            "shipTo": {
                "addressVerified": None,
                "city": "JACKSONVILLE",
                "company": None,
                "country": "US",
                "name": "Yep Example",
                "phone": "",
                "postalCode": "34567-1234",
                "residential": None,
                "state": "MN",
                "street1": "4 March St",
                "street2": "",
                "street3": None,
            },
            "shipmentCost": 2.35,
            "shipmentId": 123456789,
            "shipmentItems": None,
            "trackingNumber": "9400111899562764290090",
            "userId": "2be5d7cc-8f49-4250-9c77-dd1d5f259a3a",
            "voidDate": None,
            "voided": False,
            "warehouseId": 12345,
            "weight": {"WeightUnits": 1, "units": "ounces", "value": 6.0},
        },
    ],
    "total": 3,
}


LIST_FULFILLMENTS = {
    "fulfillments": [
        {
            "carrierCode": "UPS",
            "createDate": "2020-06-19T07:21:51.7730000",
            "customerEmail": "nope@example.net",
            "deliveryDate": None,
            "fulfillmentFee": 0.0,
            "fulfillmentId": 12345678,
            "fulfillmentProviderCode": None,
            "fulfillmentServiceCode": None,
            "marketplaceNotified": False,
            "notifyErrorMessage": None,
            "orderId": 123456789,
            "orderNumber": "4229",
            "shipDate": "2020-06-19T00:00:00.0000000",
            "shipTo": {
                "addressVerified": None,
                "city": "ROME",
                "company": "",
                "country": "US",
                "name": "Nope Example",
                "phone": "123456789",
                "postalCode": "99999-1234",
                "residential": None,
                "state": "CT",
                "street1": "0 Lost Way",
                "street2": "",
                "street3": None,
            },
            "trackingNumber": "1Z4X53V5032442XXXX",
            "userId": "98f7eab4-4d54-43b3-81e9-187f79528765",
            "voidDate": None,
            "voidRequested": False,
            "voided": False,
        },
        {
            "carrierCode": None,
            "createDate": "2020-06-24T10:32:33.3730000",
            "customerEmail": "yep@example.com",
            "deliveryDate": None,
            "fulfillmentFee": 0.0,
            "fulfillmentId": 23456789,
            "fulfillmentProviderCode": None,
            "fulfillmentServiceCode": None,
            "marketplaceNotified": False,
            "notifyErrorMessage": "IntegrationError: Shopify encountered an error and responded with StatusCode UnprocessableEntity",
            "orderId": 123456789,
            "orderNumber": "1234",
            "shipDate": "2020-06-24T10:32:33.6870000",
            "shipTo": {
                "addressVerified": None,
                "city": "CONCORD",
                "company": "Arbitrary LLC",
                "country": "US",
                "name": "Dan Arbitrary",
                "phone": "+12346789",
                "postalCode": "99999-1234",
                "residential": None,
                "state": "MT",
                "street1": "7 Some St",
                "street2": "",
                "street3": None,
            },
            "trackingNumber": "",
            "userId": "2ce23917-3e8e-485b-9853-20fde97783ea",
            "voidDate": None,
            "voidRequested": False,
            "voided": False,
        },
    ],
    "page": 1,
    "pages": 1,
    "total": 2,
}
